import {
  HiOutlineCircleStack,
  HiOutlineCog8Tooth,
  HiOutlinePencilSquare,
  HiOutlineBolt,
  HiOutlineUserCircle,
  HiOutlineUser,
  HiOutlineCodeBracket,
  HiOutlineTableCells,
  HiOutlineChevronDown,
  HiOutlineChevronRight,
  HiOutlineChevronLeft,
  HiOutlineListBullet,
  HiOutlineFunnel,
  HiOutlineInformationCircle,
  HiOutlineExclamationCircle,
  HiOutlineCheckCircle,
  HiOutlineExclamationTriangle,
  HiOutlineDocumentText,
  HiOutlineDocumentPlus,
  HiOutlineRocketLaunch,
  HiOutlinePlus,
  HiOutlineChevronUpDown,
  HiOutlineCheck,
  HiOutlineCheckBadge,
  HiOutlineXMark,
  HiServerStack,
  HiOutlinePencil,
  HiOutlineQuestionMarkCircle,
  HiOutlineArrowTopRightOnSquare,
  HiArrowDownTray,
  HiOutlineStar,
  HiStar,
} from "react-icons/hi2"
import { CiLogout } from "react-icons/ci"
import { FaDocker, FaGithub } from "react-icons/fa6"
import { TbSql } from "react-icons/tb"
import { PiAsteriskLight, PiPushPinLight } from "react-icons/pi"

export {
  HiOutlineCircleStack as DatabaseIcon,
  HiOutlineCog8Tooth as SettingsIcon,
  HiOutlinePencilSquare as IdeIcon,
  HiOutlineBolt as ExtensionsIcon,
  HiOutlineCodeBracket as ActionIcon,
  HiOutlineTableCells as TableIcon,
  HiOutlineUserCircle as ProfileIcon,
  HiOutlineChevronDown as ChevronDownIcon,
  HiOutlineChevronRight as ChevronRightIcon,
  HiOutlineChevronLeft as ChevronLeftIcon,
  HiOutlineListBullet as SortIcon,
  HiOutlineFunnel as FilterIcon,
  HiOutlineInformationCircle as InfoIcon,
  HiOutlineExclamationCircle as ErrorIcon,
  HiOutlineCheckCircle as SuccessIcon,
  HiOutlineExclamationTriangle as WarningIcon,
  HiOutlineDocumentText as FileIcon,
  HiOutlineDocumentPlus as FileCreateIcon,
  HiOutlineRocketLaunch as DeployIcon,
  HiOutlinePlus as PlusIcon,
  HiOutlineChevronUpDown as ChevronUpDownIcon,
  HiOutlineCheck as CheckIcon,
  HiOutlineCheckBadge as VerifiedIcon,
  HiOutlineUserCircle as PublisherIcon,
  HiOutlineXMark as CloseIcon,
  HiServerStack as ProviderIcon,
  HiOutlineUser as UserIcon,
  HiOutlinePencil as EditIcon,
  HiOutlineQuestionMarkCircle as HelpIcon,
  HiOutlineArrowTopRightOnSquare as FaucetIcon,
  FaGithub as GitIcon,
  FaDocker as DockerIcon,
  CiLogout as SignOutIcon,
  TbSql as QueryIcon,
  PiAsteriskLight as OtherIcon,
  HiArrowDownTray as DownloadIcon,
  HiOutlineStar as EmptyStarIcon,
  HiStar as FilledStarIcon,
  PiPushPinLight as PinIcon,
}
